//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allevasoft.Entities.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingCompanyContact
    {
        public int BillingCompanyContactId { get; set; }
        public Nullable<int> BillingCompanyId { get; set; }
        public Nullable<int> Prefix { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string OfficePhone { get; set; }
        public string OtherPhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Status { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string PostalCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
