//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allevasoft.Entities.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeadInfo()
        {
            this.LeadBillingInfoes = new HashSet<LeadBillingInfo>();
            this.LeadCareTreatments = new HashSet<LeadCareTreatment>();
            this.LeadIntakeStatus = new HashSet<LeadIntakeStatu>();
            this.LeadLevelOfCares = new HashSet<LeadLevelOfCare>();
            this.LeadEmergencyContacts = new HashSet<LeadEmergencyContact>();
        }
    
        public long LeadId { get; set; }
        public Nullable<int> ReferralCompanyId { get; set; }
        public Nullable<int> ReferralContactId { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddelName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public Nullable<int> PrimaryLanguageId { get; set; }
        public string SSNNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PostalCode { get; set; }
        public string HomeNumber { get; set; }
        public string OfficeNumber { get; set; }
        public string OtherNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> ContactType { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public Nullable<int> Relation { get; set; }
        public string ContactPhoneNumber { get; set; }
        public Nullable<int> RehabId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<System.DateTime> LastContactDate { get; set; }
        public Nullable<int> Ethnicity { get; set; }
        public Nullable<int> Race { get; set; }
        public Nullable<int> ProfileStatus { get; set; }
        public string IsAuthorized { get; set; }
        public string IsMoved { get; set; }
        public Nullable<System.DateTime> MovedLeadClientDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> LeadIntakeStatusId { get; set; }
        public Nullable<bool> IsLeadHot { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadBillingInfo> LeadBillingInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadCareTreatment> LeadCareTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadIntakeStatu> LeadIntakeStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadLevelOfCare> LeadLevelOfCares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadEmergencyContact> LeadEmergencyContacts { get; set; }
    }
}
