//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allevasoft.Entities.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadIntakeStatu
    {
        public long LeadIntakeStatus { get; set; }
        public long LeadId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime StausDate { get; set; }
        public int ChangedBy { get; set; }
    
        public virtual LeadInfo LeadInfo { get; set; }
    }
}
