//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allevasoft.Entities.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogProperty
    {
        public string TypeKey { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public bool LogValues { get; set; }
    
        public virtual LogType LogType { get; set; }
    }
}
