//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allevasoft.Entities.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientId { get; set; }
        public string Program { get; set; }
        public Nullable<System.DateTime> ProgramStartDate { get; set; }
        public string ServiceRequested { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SocialSecurityNo { get; set; }
        public Nullable<short> Weight { get; set; }
        public double Height { get; set; }
        public string FundSource { get; set; }
        public string FundSourcePolicy { get; set; }
        public string Race { get; set; }
        public string HomeAddress { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ReferralSource { get; set; }
        public string ReasonForReferral { get; set; }
        public Nullable<System.DateTime> DateOfReferral { get; set; }
        public string Siblings { get; set; }
        public string PreferredLanguage { get; set; }
        public string Ethnicity { get; set; }
        public string FullName { get; set; }
        public string EmergencyPhone { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
