//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allevasoft.Entities.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralCompany
    {
        public int ReferralCompanyId { get; set; }
        public string ReferralCompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PostalCode { get; set; }
        public string MobileNumber { get; set; }
        public string OfficeNumber { get; set; }
        public string OtherNumber { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string Website { get; set; }
        public Nullable<int> ReferralTypeId { get; set; }
        public Nullable<int> ReferralCategoryId { get; set; }
        public string StatusId { get; set; }
        public string Reason { get; set; }
        public string FacebookProfileURL { get; set; }
        public string TwitterProfileURL { get; set; }
        public string LinkedinProfileURL { get; set; }
        public string UploadDocumentName { get; set; }
        public string DocumentExtension { get; set; }
        public string DocumentFilePath { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
